/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sistemaChoferes.view;

import com.sistemaChoferes.model.clasesEntidades.Chofer;
import com.sistemaChoferes.model.clasesEntidades.Huella;
import com.sistemaChoferes.model.clasesEntidades.Rutas;
import com.sistemaChoferes.model.clasesEntidades.Vehiculo;
import com.sistemaChoferes.model.conexionBaseDatos.Conexion;
import com.sistemaChoferes.model.funcionesGestiosChoferes.RegistroChofer;
import com.sistemaChoferes.model.objetoAccesoDatos.ChoferDAO;
import com.sistemaChoferes.model.objetoAccesoDatos.HuellaDAO;
import com.sistemaChoferes.model.objetoAccesoDatos.RutasDAO;
import com.sistemaChoferes.model.objetoAccesoDatos.VehiculoDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author icruz
 */
public class viewDatosGenerales extends javax.swing.JFrame {
    
    Conexion conexion;
    Connection connection;
    DefaultTableModel defTableMod;
    Statement st;
    ResultSet rs;
    int idc;
    
    private Chofer chofer = new Chofer();
    private RegistroChofer registroChofer;
    private ChoferDAO chofeDAO;
    private HuellaDAO huellaDAO;
    private VehiculoDAO vehiculoDAO;
    private RutasDAO rutasDAO;
    private int idChofer;

    /**
     * Creates new form viewDatosGenerales
     */
    public viewDatosGenerales() {
        initComponents();
        setLocationRelativeTo(null);
        consultarTabla(idc);
    }
    
    public viewDatosGenerales(int idChofer) {
        this.idc = idChofer;
        initComponents();
        setLocationRelativeTo(null);
        consultarTabla(idc);
        registroChofer = new RegistroChofer();
        chofeDAO = new ChoferDAO();
        huellaDAO = new HuellaDAO();
        vehiculoDAO = new VehiculoDAO();
        rutasDAO = new RutasDAO();
        mostarDatos(idChofer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbHuella = new javax.swing.JLabel();
        lbPlaca = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbFechaIngreso = new javax.swing.JLabel();
        lbUltimaModificacion = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstadoChofer = new javax.swing.JTable();
        lbLlenoCedula = new javax.swing.JLabel();
        lbLlenoEstado = new javax.swing.JLabel();
        lbLlenoApellidos = new javax.swing.JLabel();
        lbLlenoFechaIn = new javax.swing.JLabel();
        lbLlenoHuella = new javax.swing.JLabel();
        lbLlenoTelefono = new javax.swing.JLabel();
        lbLlenoPlaca = new javax.swing.JLabel();
        lbLlenoRuta = new javax.swing.JLabel();
        lbLlenoNombres = new javax.swing.JLabel();
        lbLlenoFechaMod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DATOS GENERALES");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 110, -1));

        lbNombres.setText("Nombres: ");
        getContentPane().add(lbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 16, 73, -1));

        lbApellidos.setText("Apellidos:");
        getContentPane().add(lbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 38, 70, -1));

        lbCedula.setText("Id Cedula:");
        getContentPane().add(lbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 64, -1));

        lbTelefono.setText("N° telefono:");
        getContentPane().add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 60, 73, -1));

        lbHuella.setText("Id huella:");
        getContentPane().add(lbHuella, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 82, 70, -1));

        lbPlaca.setText("Placa:");
        getContentPane().add(lbPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 104, 70, -1));

        jLabel8.setText("Ruta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 126, 73, -1));

        lbFechaIngreso.setText("Fecha de ingreso:");
        getContentPane().add(lbFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 60, 150, -1));

        lbUltimaModificacion.setText("Fecha ultima modificacion:");
        getContentPane().add(lbUltimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 88, 150, -1));

        lbEstado.setText("Estado:");
        getContentPane().add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 64, -1));

        tbEstadoChofer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha ingreso", "Hora de ingreso", "estadoChofer", "autorizacinChofer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbEstadoChofer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 158, 827, 314));

        lbLlenoCedula.setText("jLabel2");
        getContentPane().add(lbLlenoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 43, 152, -1));

        lbLlenoEstado.setText("jLabel2");
        getContentPane().add(lbLlenoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 65, 152, -1));

        lbLlenoApellidos.setText("jLabel2");
        getContentPane().add(lbLlenoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 38, 152, -1));

        lbLlenoFechaIn.setText("jLabel2");
        getContentPane().add(lbLlenoFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 60, 152, -1));

        lbLlenoHuella.setText("jLabel2");
        getContentPane().add(lbLlenoHuella, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 82, 152, -1));

        lbLlenoTelefono.setText("jLabel2");
        getContentPane().add(lbLlenoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 60, 152, -1));

        lbLlenoPlaca.setText("jLabel2");
        getContentPane().add(lbLlenoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 104, 152, -1));

        lbLlenoRuta.setText("jLabel2");
        getContentPane().add(lbLlenoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 126, 152, -1));

        lbLlenoNombres.setText("jLabel2");
        getContentPane().add(lbLlenoNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 16, 152, -1));

        lbLlenoFechaMod.setText("jLabel2");
        getContentPane().add(lbLlenoFechaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 88, 152, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDatosGenerales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFechaIngreso;
    private javax.swing.JLabel lbHuella;
    private javax.swing.JLabel lbLlenoApellidos;
    private javax.swing.JLabel lbLlenoCedula;
    private javax.swing.JLabel lbLlenoEstado;
    private javax.swing.JLabel lbLlenoFechaIn;
    private javax.swing.JLabel lbLlenoFechaMod;
    private javax.swing.JLabel lbLlenoHuella;
    private javax.swing.JLabel lbLlenoNombres;
    private javax.swing.JLabel lbLlenoPlaca;
    private javax.swing.JLabel lbLlenoRuta;
    private javax.swing.JLabel lbLlenoTelefono;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbUltimaModificacion;
    private javax.swing.JTable tbEstadoChofer;
    // End of variables declaration//GEN-END:variables

    private void consultarTabla(int idc) {
        String sql = "SELECT * FROM registro_Estados WHERE id_Chofer = ?";
        sql = sql.replace("?", String.valueOf(idc));
        
        try {
            connection = conexion.conectar();
            st = connection.createStatement();
            rs = st.executeQuery(sql);
            Object[] datosChoferes = new Object[5];
            defTableMod = (DefaultTableModel) tbEstadoChofer.getModel();
            defTableMod.setRowCount(0);
            while (rs.next()) {
                datosChoferes[0] = rs.getString("fecha_Ingreso");
                datosChoferes[1] = rs.getString("hora_Ingreso");
                datosChoferes[2] = rs.getString("estado_Chofer");
                datosChoferes[3] = rs.getString("autorizacion_Chofer");

                defTableMod.addRow(datosChoferes);
            }
            tbEstadoChofer.setModel(defTableMod);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (st != null) st.close();
                if (connection != null) connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    public void mostarDatos(int idc){
        
        Chofer chofer = chofeDAO.obtenerChoferPorId(idc);
        Vehiculo vehiculo = vehiculoDAO.obtenerVehiculoPorChoferId(idc);
        Huella huella = huellaDAO.obtenerHuellaPorId(idc);
        Rutas rutas = rutasDAO.obtenerRutaPorChoferId(idc);
        
        Date fecha = huella.getFechaRegHuella();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaIngreso = sdf.format(fecha);
        
        if (chofer != null) {
            lbLlenoCedula.setText(chofer.getIdCedula());;
            lbLlenoEstado.setText("Activo");;
            lbLlenoNombres.setText(chofer.getNombre());;
            lbLlenoApellidos.setText(chofer.getApellido());;
            lbLlenoTelefono.setText(chofer.getTelefono());;
            lbLlenoPlaca.setText(vehiculo.getIdPlaca());;
            lbLlenoRuta.setText(rutas.getNombreRuta());;
            lbLlenoFechaIn.setText(fechaIngreso);
            lbLlenoFechaMod.setText(fechaIngreso);
            lbLlenoHuella.setText(huella.getIdCodigoHuella());;
        } else {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos del chofer", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
