/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sistemaChoferes.ui;

import com.sistemaChoferes.business.RegistroChofer;
import com.sistemaChoferes.business.RegistroIngreso;
import com.sistemaChoferes.dataacess.dao.ChoferDAO;
import com.sistemaChoferes.dataacess.dao.HuellaDAO;
import com.sistemaChoferes.dataacess.dao.RutasDAO;
import com.sistemaChoferes.dataacess.dao.VehiculoDAO;
import com.sistemaChoferes.dataacess.datahelper.DataHelper;
import com.sistemaChoferes.dataacess.entity.Chofer;
import com.sistemaChoferes.dataacess.entity.Huella;
import com.sistemaChoferes.dataacess.entity.Rutas;
import com.sistemaChoferes.dataacess.entity.Vehiculo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author icruz
 */
public class DatosChofer extends javax.swing.JFrame {
    private int idChofer;
    private ChoferDAO chofeDAO;
    private VehiculoDAO vehiculoDAO;
    private RutasDAO rutasDAO;
    private RegistroIngreso registroIngreso;
    
    /**
     * Creates new form DatosChofer
     */
    public DatosChofer() {
        initComponents();
    }
    
    public DatosChofer(int idc) throws Exception{
        this.idChofer = idc;
        initComponents();
        setLocationRelativeTo(null);
        chofeDAO = new ChoferDAO();
        vehiculoDAO = new VehiculoDAO();
        rutasDAO = new RutasDAO();
        registroIngreso = new RegistroIngreso();
        mostrarDatos(idChofer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLNombreCompleto = new javax.swing.JLabel();
        jLCedula = new javax.swing.JLabel();
        jLRuta = new javax.swing.JLabel();
        jLPlaca = new javax.swing.JLabel();
        jLFechaIngreso = new javax.swing.JLabel();
        jLHoraIngreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DATOS GENERALES DEL TRANSPORTISTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 23, -1, -1));

        jLabel2.setText("Datos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 57, 37, -1));

        jLabel3.setText("Nombre Completo del transportista");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 200, -1));

        jLabel4.setText("CD. Transportista");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 181, 200, -1));

        jLabel5.setText("Ruta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, -1));

        jLabel6.setText("Placa del transportista");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, -1));

        jLabel7.setText("Hora de ingreso");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 200, -1));

        jLabel8.setText("Fecha de ingreso");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 200, -1));

        jButton1.setText("TEST ALCOHOLEMIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jLNombreCompleto.setText("jLabel9");
        getContentPane().add(jLNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 200, -1));

        jLCedula.setText("jLabel10");
        getContentPane().add(jLCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 203, 200, -1));

        jLRuta.setText("jLabel11");
        getContentPane().add(jLRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, -1));

        jLPlaca.setText("jLabel12");
        getContentPane().add(jLPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 200, -1));

        jLFechaIngreso.setText("jLabel13");
        getContentPane().add(jLFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 200, -1));

        jLHoraIngreso.setText("jLabel14");
        getContentPane().add(jLHoraIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TestAlcohol testAlcohol = new TestAlcohol(idChofer);
        testAlcohol.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void mostrarDatos(int idChofer) throws Exception {
        Chofer chofer = chofeDAO.readBy(idChofer);
        Vehiculo vehiculo = vehiculoDAO.obtenerVehiculoPorChoferId(idChofer);
        Rutas rutas = rutasDAO.obtenerRutaPorChoferId(idChofer);

        if (chofer != null && vehiculo != null && rutas != null) {
            jLCedula.setText(chofer.getIdCedula());
            jLNombreCompleto.setText(chofer.getNombre() + " " + chofer.getApellido());
            jLPlaca.setText(vehiculo.getIdPlaca());
            jLRuta.setText(rutas.getNombreRuta());

            LocalDate fechaIngreso = LocalDate.now();
            LocalTime horaIngreso = LocalTime.now();

            jLFechaIngreso.setText(fechaIngreso.toString());
            jLHoraIngreso.setText(horaIngreso.toString());

            registroIngreso.registrarIngreso(idChofer, false);

        } else {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos del chofer, vehículo o ruta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DatosChofer(1).setVisible(true); // Solo para pruebas, idChofer=1
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLFechaIngreso;
    private javax.swing.JLabel jLHoraIngreso;
    private javax.swing.JLabel jLNombreCompleto;
    private javax.swing.JLabel jLPlaca;
    private javax.swing.JLabel jLRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    
}
