package com.sistemaChoferes.ui;
import com.sistemaChoferes.dataacess.dto.Validaciones;
import com.sistemaChoferes.dataacess.entity.Chofer;
import com.sistemaChoferes.dataacess.entity.Huella;
import com.sistemaChoferes.dataacess.entity.Rutas;
import com.sistemaChoferes.dataacess.entity.Vehiculo;
import com.sistemaChoferes.business.RegistroChofer;
import com.sistemaChoferes.dataacess.dao.ChoferDAO;
import com.sistemaChoferes.dataacess.dao.HuellaDAO;
import com.sistemaChoferes.dataacess.dao.RutasDAO;
import com.sistemaChoferes.dataacess.dao.VehiculoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class formularioIngreso extends javax.swing.JFrame {
    private Chofer chofer = new Chofer();
    private RegistroChofer registroChofer;
    private ChoferDAO chofeDAO;
    private HuellaDAO huellaDAO;
    private VehiculoDAO vehiculoDAO;
    private RutasDAO rutasDAO;
    private int idChofer;
    
    public int getIdChofer() {
        return idChofer;
    }
    
    private void setIdChofer(int idChofer) {
        this.idChofer = idChofer;
    }

    public formularioIngreso() {
        initComponents();
        setLocationRelativeTo(null);
        registroChofer = new RegistroChofer();
        btnActualizar.setVisible(false);
    }
    
    public formularioIngreso(int idChofer) throws Exception {
        this.idChofer = idChofer;
        initComponents();
        setLocationRelativeTo(null);
        registroChofer = new RegistroChofer();
        chofeDAO = new ChoferDAO();
        huellaDAO = new HuellaDAO();
        vehiculoDAO = new VehiculoDAO();
        rutasDAO = new RutasDAO();
        mostarDatos(idChofer);
        btnGuardar.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDtosGenerales = new javax.swing.JPanel();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtHuella = new javax.swing.JTextField();
        txtCategoriaLicencia = new javax.swing.JTextField();
        in_Cedula = new javax.swing.JLabel();
        in_Nombre = new javax.swing.JLabel();
        in_Apellido = new javax.swing.JLabel();
        in_Telefono = new javax.swing.JLabel();
        in_Correo = new javax.swing.JLabel();
        in_Direccion = new javax.swing.JLabel();
        in_Huella = new javax.swing.JLabel();
        in_CatLicencia = new javax.swing.JLabel();
        in_FechaVencimientoLicencia = new javax.swing.JLabel();
        txtFechaVencimientoLicencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlDatosVehiculo = new javax.swing.JPanel();
        txtVehiculo = new javax.swing.JTextField();
        txtRuta = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtMarcaVehiculo = new javax.swing.JTextField();
        txtModeloVehiculo = new javax.swing.JTextField();
        in_Placa = new javax.swing.JLabel();
        in_TipoVehiculo = new javax.swing.JLabel();
        in_Ruta = new javax.swing.JLabel();
        in_MarcaVehiculo = new javax.swing.JLabel();
        in_ModeloVehiculo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 610));
        setResizable(false);
        setSize(new java.awt.Dimension(798, 582));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDtosGenerales.setBackground(new java.awt.Color(102, 102, 102));
        pnlDtosGenerales.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlDtosGeneralesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtHuella.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHuella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHuellaActionPerformed(evt);
            }
        });

        txtCategoriaLicencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCategoriaLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaLicenciaActionPerformed(evt);
            }
        });

        in_Cedula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Cedula.setText("N° Cedula:");

        in_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Nombre.setText("Nombre:");

        in_Apellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Apellido.setText("Apellido:");

        in_Telefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Telefono.setText("Telefono:");

        in_Correo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Correo.setText("Correo:");

        in_Direccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Direccion.setText("Direccion:");

        in_Huella.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Huella.setText("ID Huella:");

        in_CatLicencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_CatLicencia.setText("Categotia de licencia:");

        in_FechaVencimientoLicencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_FechaVencimientoLicencia.setText("Fecha vencimiento Licencia:");

        txtFechaVencimientoLicencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechaVencimientoLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVencimientoLicenciaActionPerformed(evt);
            }
        });

        jLabel2.setText("DATOS PERSONALES");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/huella.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout pnlDtosGeneralesLayout = new javax.swing.GroupLayout(pnlDtosGenerales);
        pnlDtosGenerales.setLayout(pnlDtosGeneralesLayout);
        pnlDtosGeneralesLayout.setHorizontalGroup(
            pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_CatLicencia)
                    .addComponent(txtCategoriaLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_FechaVencimientoLicencia)
                    .addComponent(txtFechaVencimientoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHuella, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_Huella, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlDtosGeneralesLayout.setVerticalGroup(
            pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                        .addComponent(in_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(in_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(in_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                        .addComponent(in_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(in_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(in_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                        .addComponent(in_FechaVencimientoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaVencimientoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoriaLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlDtosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDtosGeneralesLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtHuella, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(in_Huella, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(in_CatLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(pnlDtosGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 770, 280));

        pnlDatosVehiculo.setBackground(new java.awt.Color(102, 102, 102));

        txtVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiculoActionPerformed(evt);
            }
        });

        txtRuta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });

        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtMarcaVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMarcaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaVehiculoActionPerformed(evt);
            }
        });

        txtModeloVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtModeloVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloVehiculoActionPerformed(evt);
            }
        });

        in_Placa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Placa.setText("Placa:");

        in_TipoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_TipoVehiculo.setText("Tipo vehiculo:");

        in_Ruta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_Ruta.setText("Ruta:");

        in_MarcaVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_MarcaVehiculo.setText("Marca:");

        in_ModeloVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        in_ModeloVehiculo.setText("Modelo:");

        jLabel3.setText("DATOS DEL VEHICULO");

        javax.swing.GroupLayout pnlDatosVehiculoLayout = new javax.swing.GroupLayout(pnlDatosVehiculo);
        pnlDatosVehiculo.setLayout(pnlDatosVehiculoLayout);
        pnlDatosVehiculoLayout.setHorizontalGroup(
            pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_MarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_TipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_ModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        pnlDatosVehiculoLayout.setVerticalGroup(
            pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_TipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_ModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(in_MarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(pnlDatosVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 640, 230));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 89, -1));

        btnActualizar.setBackground(new java.awt.Color(204, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));

        jLabel1.setText("FORMULARIO DE INGRESO DE DATOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehiculoActionPerformed

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaActionPerformed

    private void txtHuellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHuellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHuellaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String cedula = txtCedula.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String direccion = txtDireccion.getText();
        String huella = txtHuella.getText();
        String placa = txtPlaca.getText();
        String vehiculo = txtVehiculo.getText();
        String ruta = txtRuta.getText();
        String modeloVehiculo = txtModeloVehiculo.getText();
        String marcaVehiculo = txtMarcaVehiculo.getText();
        String categoriaLicencia = txtCategoriaLicencia.getText();
        String fechaVencimientoLicenciaStr = txtFechaVencimientoLicencia.getText();

        if (cedula.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || telefono.isEmpty() ||
            placa.isEmpty() || vehiculo.isEmpty() || ruta.isEmpty() || huella.isEmpty() || correo.isEmpty() ||
            direccion.isEmpty() || modeloVehiculo.isEmpty() || marcaVehiculo.isEmpty() || categoriaLicencia.isEmpty() || fechaVencimientoLicenciaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser llenados.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        Validaciones validaciones = new Validaciones();

        boolean banderaID = false;
        boolean banderaNombre = false;
        boolean banderaApellido = false;
        boolean banderaTelefono = false;
        boolean banderaPlaca = false;
        boolean banderaIDHuella = false;
        boolean banderaMarca = false;
        boolean banderaModelo = false;

        while (banderaID == false){
            if (cedula.length()==10){
                banderaID = true;
            } else {
                JOptionPane.showMessageDialog(this, "El ID que ha ingresado no contiene exactamente 10 numeros, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (validaciones.validarBanderas(cedula.length(), cedula) == false){
                JOptionPane.showMessageDialog(this, "El ID ingresado contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaID = true;
            }
            
        }
        
        while (banderaNombre == false){
            if (validaciones.validarBanderas(nombres.length(), nombres) == false){
                JOptionPane.showMessageDialog(this, "El nombre ingresado contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaNombre = true;
            }
        }
        
        while (banderaApellido == false){
            if (validaciones.validarBanderas(apellidos.length(), apellidos) == false){
                JOptionPane.showMessageDialog(this, "El apellido ingresado contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaApellido = true;
            }
        }

        while (banderaTelefono == false){
            if (telefono.length()==10){
                banderaTelefono = true;
            } else {
                JOptionPane.showMessageDialog(this, "El numero de telefono que ha ingresado no contiene exactamente 10 numeros, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (validaciones.validarBanderas(telefono.length(), telefono) == false){
                JOptionPane.showMessageDialog(this, "El telefono ingresado contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaTelefono = true;
            }
        }
        
        while (banderaIDHuella == false){ 
            if (validaciones.validarBanderas(huella.length(), huella) == false){
                JOptionPane.showMessageDialog(this, "La ID de la huella ingresada contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaIDHuella = true;
            }
        }
        
        while (banderaPlaca == false){
            if (placa.length()==7){
                banderaPlaca = true;
            } else {
                JOptionPane.showMessageDialog(this, "La placa que ha ingresado no contiene exactamente 7 caracteres, vuelvala a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (validaciones.validarBanderas(placa.length(), placa) == false){
                JOptionPane.showMessageDialog(this, "La placa ingresada contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaPlaca = true;
            }
        }

        while (banderaModelo == false){ 
            
            if (validaciones.validarBanderas(modeloVehiculo.length(), modeloVehiculo) == false){
                JOptionPane.showMessageDialog(this, "El modelo de vehiculo ingresado contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaModelo = true;
            }
        }

        while (banderaMarca == false){ 
            
            if (validaciones.validarBanderas(marcaVehiculo.length(), marcaVehiculo) == false){
                JOptionPane.showMessageDialog(this, "La marca del vehiculo ingresado contiene un espacio, vuelvalo a ingresar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                banderaMarca = true;
            }
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date fechaVencimientoLicencia;
        try {
            java.util.Date parsedDate = dateFormat.parse(fechaVencimientoLicenciaStr);
            fechaVencimientoLicencia = new java.sql.Date(parsedDate.getTime());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha no válido. Use el formato 'yyyy-MM-dd'.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            idChofer = registroChofer.registrarNuevoChofer(cedula, nombres, apellidos, telefono, huella, placa, vehiculo, ruta, direccion, correo, categoriaLicencia, fechaVencimientoLicencia, marcaVehiculo, modeloVehiculo);
            JOptionPane.showMessageDialog(this, "Registro guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            listadoChoferesCRUD.datosAgregados = true;
            this.dispose();
            if (listadoChoferesCRUD.listadoChoferesInstance != null) {
                listadoChoferesCRUD.listadoChoferesInstance.actualizarTabla();
            } else {
                System.out.println("Error: listadoChoferesInstance es null.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el registro: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void mostarDatos(int idc) throws Exception{
    Chofer chofer = chofeDAO.readBy(idc);
    Vehiculo vehiculo = vehiculoDAO.obtenerVehiculoPorChoferId(idc);
    Huella huella = huellaDAO.obtenerHuellaPorChoferId(idc);
    Rutas rutas = rutasDAO.obtenerRutaPorChoferId(idc);

    if (chofer != null) {
        txtNombres.setText(chofer.getNombre());
        txtApellidos.setText(chofer.getApellido());
        txtCedula.setText(chofer.getIdCedula());
        txtTelefono.setText(chofer.getTelefono());
        txtCorreo.setText(chofer.getCorreo());  
        txtDireccion.setText(chofer.getDireccion());
        txtCategoriaLicencia.setText(chofer.getCategoriaLicencia());

        if (chofer.getFechaVencimientoLicencia()!= null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String fechaFormateada = dateFormat.format(chofer.getFechaVencimientoLicencia());
            txtFechaVencimientoLicencia.setText(fechaFormateada);
        } else {
            txtFechaVencimientoLicencia.setText("");
        }

        if (vehiculo != null) {
            txtPlaca.setText(vehiculo.getIdPlaca());
            txtVehiculo.setText(vehiculo.getTipoVehiculo());
            txtMarcaVehiculo.setText(vehiculo.getMarcaVehiculo());
            txtModeloVehiculo.setText(vehiculo.getModeloVehiculo());
        }
        if (rutas != null) {
            txtRuta.setText(rutas.getNombreRuta());
        }
        if (huella != null) {
            txtHuella.setText(huella.getIdCodigoHuella());
        }
        } else {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos del chofer", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    
    
    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres cancelar el ingreso?", "Confirmación", JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
           dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres actualizar los nuevos datos?", "Confirmación", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            String cedula = txtCedula.getText();
            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            String direccion = txtDireccion.getText();
            String huella = txtHuella.getText();
            String placa = txtPlaca.getText();
            String vehiculo = txtVehiculo.getText();
            String ruta = txtRuta.getText();
            String modeloVehiculo = txtModeloVehiculo.getText();
            String marcaVehiculo = txtMarcaVehiculo.getText();
            String categoriaLicencia = txtCategoriaLicencia.getText();
            String fechaVencimientoLicenciaStr = txtFechaVencimientoLicencia.getText();

            if (cedula.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || telefono.isEmpty() ||
                placa.isEmpty() || vehiculo.isEmpty() || ruta.isEmpty() || huella.isEmpty() || correo.isEmpty() ||
                direccion.isEmpty() || modeloVehiculo.isEmpty() || marcaVehiculo.isEmpty() || categoriaLicencia.isEmpty() || fechaVencimientoLicenciaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos deben ser llenados.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.sql.Date fechaVencimientoLicencia;
            try {
                java.util.Date parsedDate = dateFormat.parse(fechaVencimientoLicenciaStr);
                fechaVencimientoLicencia = new java.sql.Date(parsedDate.getTime());
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha no válido. Use el formato 'yyyy-MM-dd'.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                registroChofer.actualizarChofer(idChofer, cedula, nombres, apellidos, telefono, huella, placa, vehiculo, ruta, direccion, correo, categoriaLicencia, fechaVencimientoLicencia, marcaVehiculo, modeloVehiculo);
                JOptionPane.showMessageDialog(this, "Registro actualizado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                listadoChoferesCRUD.datosActualizados = true;
                limpiarCampos();
                this.dispose();
                if (listadoChoferesCRUD.listadoChoferesInstance != null) {
                    listadoChoferesCRUD.listadoChoferesInstance.actualizarTabla();
                } else {
                    System.out.println("Error: listadoChoferesInstance es null.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el registro: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtMarcaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaVehiculoActionPerformed

    private void txtModeloVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloVehiculoActionPerformed

    private void txtCategoriaLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaLicenciaActionPerformed

    private void txtFechaVencimientoLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVencimientoLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVencimientoLicenciaActionPerformed

    private void pnlDtosGeneralesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlDtosGeneralesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDtosGeneralesAncestorAdded
  
    private void limpiarCampos(){
        txtCedula.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtHuella.setText("");
        txtPlaca.setText("");
        txtVehiculo.setText("");
        txtRuta.setText("");
        txtModeloVehiculo.setText("");
        txtMarcaVehiculo.setText("");
        txtCategoriaLicencia.setText("");
        txtFechaVencimientoLicencia.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel in_Apellido;
    private javax.swing.JLabel in_CatLicencia;
    private javax.swing.JLabel in_Cedula;
    private javax.swing.JLabel in_Correo;
    private javax.swing.JLabel in_Direccion;
    private javax.swing.JLabel in_FechaVencimientoLicencia;
    private javax.swing.JLabel in_Huella;
    private javax.swing.JLabel in_MarcaVehiculo;
    private javax.swing.JLabel in_ModeloVehiculo;
    private javax.swing.JLabel in_Nombre;
    private javax.swing.JLabel in_Placa;
    private javax.swing.JLabel in_Ruta;
    private javax.swing.JLabel in_Telefono;
    private javax.swing.JLabel in_TipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlDatosVehiculo;
    private javax.swing.JPanel pnlDtosGenerales;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCategoriaLicencia;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaVencimientoLicencia;
    private javax.swing.JTextField txtHuella;
    private javax.swing.JTextField txtMarcaVehiculo;
    private javax.swing.JTextField txtModeloVehiculo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}
